### ISSUE TITLE
HardFault error when running brute/Pause.sub

### ISSUE THREAD

**Issue by JohnELester** [jimilinuxguy/flipperzero-touchtunes#1] opened 2022-05-08 13:58 UTC
Getting a HardFault error when running https://github.com/jimilinuxguy/flipperzero-touchtunes/blob/master/brute/Pause.sub

https://user-images.githubusercontent.com/25461543/167299725-daef2d9b-92ea-4b35-903e-7d4e78089706.mp4

**Comment by skotopes** [comment] 2022-05-08 14:33
Issue caused by incorrect data: payload must not contain 2 levels of same sign in the sequence. 
In this file line ends with positive number and then next line starts with positive number. We automatically inject low level to end transmission but transmission is not ending and then we have buffer overrun.

**Comment by jimilinuxguy** [comment] 2022-05-08 15:55
@JohnELester I updated the brute force signals based on the comment from @skotopes above (thanks!)

If you can verify that they are no longer causing a HardFault issue, I will merge to master and close this ticket out.

I visually checked every-one, but have only tested every-other one.

**Comment by JohnELester** [comment] 2022-05-08 17:50
Confirmed. The latest version of https://github.com/jimilinuxguy/flipperzero-touchtunes/blob/master/brute/Pause.sub now runs with no errors.

**Closed as completed** 2022-05-08 19:44 UTC
